baseURL = "/"
languageCode = "pt-br"
title = "Hercilio Lopes"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  defaultTheme = "auto"
  hideFooter = true
  # Configurações de busca
  ShowSearch = true
  #ShowToc = true
  #TocOpen = false
  # Configurações de output
  outputDir = "public"
  disableKinds = []
  enableGitInfo = true
  enableEmoji = true
  enableRobotsTXT = true
  ShowCodeCopyButtons = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Início"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categorias"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "search"
    name = "Buscar"
    url = "/search/"
    weight = 40

  [[menu.main]]
  name = "Arquivos"
  url = "/archives/"
  weight = 50


